### ISSUE TITLE
How it work ?

### ISSUE THREAD

**Issue by dlepaux** [myers/chord_detector#1]
Hello @myers,

Thank you for sharing your work !
I would like to use your package but I have not arrived.

You say in the readme to do some stuff but I don't see where do theses things..
Could you help me?

**Comment by myers** [comment]
@dlepaux sorry I missed you until now.  The commands I have are to rebuild the package.  You shouldn't have to do this unless you make some tweaks to the code.  You will want to look at the docs directory specifically at https://github.com/myers/chord_detector/blob/master/docs/demo.js on how to use this.
